#!/bin/bash
SESSION=$USER
cd ~/proyectos

tmux -2 new-session -d -s $SESSION

# Setup a window for tailing log files

tmux new-window -t $SESSION:1 -n 'Logs'
tmux split-window -h
tmux select-pane -t 0
tmux send-keys "vagrant ssh" C-m

tmux select-pane -t 1
tmux send-keys "vagrant up" C-m
tmux split-window -v

tmux resize-pane -D 40
tmux send-keys "top" C-m

# Setup a CoffeeScript compiler/watchdog pane
tmux select-pane -t 0
tmux split-window -v
tmux resize-pane -D 40
tmux send-keys "echo 'zzzzzzzzzzzzzzzzz'" C-m

# Setup a MySQL window
tmux new-window -t $SESSION:2 -n 'MySQL' 'mysql -uroot'

# Set default window
tmux select-window -t $SESSION:1

# Attach to session
tmux -2 attach-session -t $SESSION